"""Tests for the P0-09 synthetic-proxy retry-behavior detector.

Two kinds of test here:

1. Hand-built envelope fixtures with an obvious gap+burst pattern and an obvious "nothing
   happened" pattern, so the detector's core logic is pinned down independent of the fixture
   generator's randomness.
2. A cross-check against `tests/fixtures/generators/supercharger.py`'s own synthetic ground
   truth (`_debug_injected_issues` containing "post_outage_burst"). This is the ONLY place in
   this codebase allowed to read that field for anything other than generator-testing
   purposes - profiling/retry_behavior/profiler.py never reads it (see that module's
   docstring: a real device would never send it).

Honest framing, worth repeating here because it's easy to lose in a wall of numbers: this
cross-check measures how well a gap+batch-size heuristic recovers a *known synthetic*
ground truth generated by a simple simulation. It is evidence about how hard this detection
problem is in principle, and about this specific heuristic's behavior - it is NOT validated
against, and cannot stand in for, real device behavior. See
docs/profiling/P0-09-retry-behavior-test-plan.md for the actual real-hardware test plan.
"""
from __future__ import annotations

from profiling.retry_behavior.profiler import (
    MIN_MESSAGES_FOR_BASELINE,
    detect_buffer_burst_events,
    group_messages_by_device,
    profile_messages,
)
from tests.fixtures.generators.supercharger import GeneratorConfig, generate


def _msg(device_id: str, message_id: str, arrival_ts_ms: int, num_readings: int) -> dict:
    """Minimal envelope stub with only the fields the detector reads."""
    return {
        "device_id": device_id,
        "message_id": message_id,
        "arrival_ts_ms": arrival_ts_ms,
        "readings": [{"device_ts_ms": arrival_ts_ms} for _ in range(num_readings)],
    }


def _regular_cadence_messages(
    device_id: str, count: int, interval_ms: int = 60_000, batch_size: int = 4
) -> list[dict]:
    return [
        _msg(device_id, f"{device_id}-msg{i}", i * interval_ms, batch_size) for i in range(count)
    ]


def test_regular_cadence_produces_no_events():
    """A device with steady gaps and steady batch sizes should never be flagged."""
    messages = _regular_cadence_messages("dev-steady", count=20)
    events = detect_buffer_burst_events(messages)
    assert events == []


def test_clear_gap_and_burst_is_flagged():
    """A long quiet gap followed by an oversized batch is exactly the signature the detector
    is built to catch."""
    messages = _regular_cadence_messages("dev-outage", count=10, interval_ms=60_000, batch_size=4)
    # Replace the last message with one that arrives ~20x the normal gap later, carrying a
    # batch ~4x the normal size - the buffered-burst shape.
    burst = _msg("dev-outage", "dev-outage-burst", 9 * 60_000 + 20 * 60_000, num_readings=16)
    messages = messages[:-1] + [burst]

    events = detect_buffer_burst_events(messages)

    assert len(events) == 1
    event = events[0]
    assert event.message_id == "dev-outage-burst"
    assert event.gap_ratio > 3.0
    assert event.batch_size_ratio > 0.5
    assert event.batch_size == 16


def test_long_gap_alone_is_not_enough_without_a_non_trivial_batch():
    """A long gap followed by a single-reading trickle (not a burst) should NOT be flagged -
    this pins down that both conditions (gap AND batch size) are required, matching the
    module's documented reasoning that gap alone isn't sufficient corroboration."""
    messages = _regular_cadence_messages("dev-trickle", count=10, interval_ms=60_000, batch_size=4)
    tiny_late = _msg("dev-trickle", "dev-trickle-tiny", 9 * 60_000 + 20 * 60_000, num_readings=1)
    messages = messages[:-1] + [tiny_late]

    events = detect_buffer_burst_events(messages)
    assert events == []


def test_too_few_messages_for_baseline_never_flags():
    """Below MIN_MESSAGES_FOR_BASELINE there isn't enough history to know what's "unusual"
    for this device, so nothing should be flagged even if the raw numbers look extreme."""
    assert MIN_MESSAGES_FOR_BASELINE >= 4
    messages = [
        _msg("dev-new", "dev-new-0", 0, num_readings=1),
        _msg("dev-new", "dev-new-1", 60_000, num_readings=1),
        _msg("dev-new", "dev-new-2", 10_000_000, num_readings=50),
    ]
    assert len(messages) < MIN_MESSAGES_FOR_BASELINE
    events = detect_buffer_burst_events(messages)
    assert events == []


def test_group_messages_by_device_and_profile_messages_shape():
    messages = _regular_cadence_messages("dev-a", count=6) + _regular_cadence_messages(
        "dev-b", count=6
    )
    by_device = group_messages_by_device(messages)
    assert set(by_device.keys()) == {"dev-a", "dev-b"}

    profile = profile_messages(messages, "supercharger_stall", "9.9.9")
    assert profile.device_count == 2
    assert profile.devices_with_events == 0
    assert profile.events == []


# --- Cross-check against the fixture generator's synthetic ground truth ---------------------
#
# devices_per_firmware=4 matches the generator's own default scale (small, fast, deterministic
# given the default seed). At this scale the *count* of true post_outage_burst events is small
# (order ten), so treat the exact numbers below as illustrative of ballpark behavior, not a
# precise estimate - see the larger-sample notes in the comment after the test.


def test_detector_against_generator_ground_truth_reports_honest_accuracy():
    fixtures = generate(GeneratorConfig(devices_per_firmware=4))

    devices_with_true_burst = 0
    devices_detector_hit_the_true_burst_message = 0
    true_burst_messages = 0
    true_burst_messages_flagged = 0
    total_flagged = 0
    total_flagged_correct = 0

    for messages in fixtures.messages_by_group.values():
        for device_messages in group_messages_by_device(messages).values():
            true_burst_ids = {
                m["message_id"]
                for m in device_messages
                if "post_outage_burst" in m["_debug_injected_issues"]
            }
            events = detect_buffer_burst_events(device_messages)
            flagged_ids = {e.message_id for e in events}

            if true_burst_ids:
                devices_with_true_burst += 1
                if true_burst_ids & flagged_ids:
                    devices_detector_hit_the_true_burst_message += 1

            true_burst_messages += len(true_burst_ids)
            true_burst_messages_flagged += len(true_burst_ids & flagged_ids)
            total_flagged += len(flagged_ids)
            total_flagged_correct += len(flagged_ids & true_burst_ids)

    assert devices_with_true_burst > 0, "generator produced no outage events - test is vacuous"

    recall = true_burst_messages_flagged / true_burst_messages
    precision = total_flagged_correct / total_flagged if total_flagged else 0.0
    device_recall = devices_detector_hit_the_true_burst_message / devices_with_true_burst

    # Honest, real numbers measured at this scale (default seed 1337, devices_per_firmware=4):
    # recall ~0.40 (4/10 true burst messages caught), device-level recall ~0.44 (4/9 devices
    # with a real outage get their actual burst message flagged), message-level precision
    # ~0.04 (4/107 flagged candidates are real) - most flagged candidates are false alarms,
    # dominated by the generator's independent ~6% late_arrival injection rate, which produces
    # the same "isolated long gap" signature as a real outage from the arrival-time series
    # alone. See profiler.py's module docstring for why batch size doesn't disambiguate this
    # well in this generator. The bounds below are loose on purpose (checked across several
    # seeds during development, recall ranged ~0.4-0.67 at this small sample size) so this
    # test isn't flaky while still catching a real regression in the detector.
    assert recall >= 0.25, f"recall unexpectedly low: {recall:.3f} ({true_burst_messages_flagged}/{true_burst_messages})"
    assert device_recall >= 0.25, f"device-level recall unexpectedly low: {device_recall:.3f}"
    # Precision is genuinely mediocre against this synthetic ground truth (see docstring above
    # and profiler.py) - assert only that it's non-zero (the detector isn't pure noise) and
    # not implausibly high (which would suggest this test's math is wrong, not that the
    # detector got much better).
    assert 0.0 < precision < 0.5, f"precision out of the expected mediocre range: {precision:.3f}"
